### ISSUE TITLE
Find a way to get labels and labels_de?

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/collect_stata#16]
I looked at your approach in 
https://github.com/ddionrails/ddi.py/blob/stata_to_json/ddi/stata_to_json/scripts/stata_to_json.py

Is it planned to include `labels_de` in `collect_stata`? If yes, how?

**Comment by mpahl** [comment]
It is possible if there are two stata files in english and german. Imports of both files give bilingual labels.
Extract two languages from a single dta file is impossible atm.

**Comment by afuetterer** [comment]
It is possible right now? If yes, how?

The two languages from a single dta file approach could be postponed, I guess?

**Comment by mpahl** [comment]
It's not possible now as far as I know.

**Comment by afuetterer** [comment]
Let me start over. :smile: 

1. It is not possible right now to read english and german labels with `collect_stata`.
Correct?
At least as far as I see, nothing appends to `labels_de`.

2. This functionality is desired.
Correct?

@hansendx What do you say?

**Comment by afuetterer** [comment]
closing this.
