### ISSUE TITLE
Migrate new scripts from ddi.py

### ISSUE THREAD

**Issue by hansendx** [ddionrails/collect_stata#2]
- The [ddi.py](https://github.com/ddionrails/ddi.py) repository is full with deprecated stuff.
- The new python scripts to transform stata files to be imported into ddionrails need a new home here
- Scripts should reside in a directory in the root called `collect_stata`
- Tests should be in a directory in the root called `tests`

**Comment by mpahl** [comment]
Scripts and so on are added locally. I can't commit current changes.
Calling commands like
collect_stata --i ~/clone/DIW/collect_stata/input/teststudy/ --o ~/clone/DIW/collect_stata/output/test/
work now.

**Comment by mpahl** [comment]
Ah, I saw the next issues...

**Comment by afuetterer** [comment]
> I can't commit current changes.

Please create a new branch and PR to develop.
