### ISSUE TITLE
What is up with those modules in ddi.py?

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/collect_stata#21]
Are these modules the same as the ones in this repo?
- https://github.com/ddionrails/ddi.py/blob/master/ddi/dataset.py
- https://github.com/ddionrails/ddi.py/tree/master/ddi/convert

Can they be removed in ddi.py?

**Comment by mpahl** [comment]
The class Dataset was once for reading either tdp or stata data and writing out stats, tdp and do files. Tests were included. 
At least the stats outfile is deprecated.
It can be removed from ddi.py if there is no interest in the convert function.

**Comment by afuetterer** [comment]
closing this.
