### ISSUE TITLE
Add test cases for __main__.py

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/collect_stata#26]
The test case right now only executes `stata_to_json()`. The CLI is not tested at all.
Please add test cases that use combinations of flags.

Like 
`collect_stata -i X -o Y`
`collect_stata -i X -o Y -v`
`collect_stata -i X -o Y --study some-study`

**Comment by hansendx** [comment]
This could be done with `unittest.mock.patch` for example

```python

from unittest.mock import patch
from collect_stata import main

def test_etc():
    ...
   _arguments = [
        '__main__.py',
        '-i',
        'X',
        '-o',
        'Y'
    ]
    with patch.object(sys, 'argv', _arguments):
            main()
```
[patch](https://docs.python.org/3/library/unittest.mock.html#the-patchers) can also be used as decorator.
