### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by hansendx** [ddionrails/collect_stata#32]
The Readme only contains basic information for installation please document:

* Production installation
* Use information
* Purpose of the project

#18

**Comment by afuetterer** [comment]
I ran into this:
https://github.com/ddionrails/ddi.py/tree/master/docs

Is this reusable in some way?

**Comment by afuetterer** [comment]
Another thing:
You wrote "pipenv install -e ." under "Setup for development". This actually altered the Pipfile and Pipfile.lock. Is this intended?
Right now running "pipenv install --dev" already installs collect_stata.

**Comment by hansendx** [comment]
> Another thing:
> You wrote "pipenv install -e ." under "Setup for development". This actually altered the Pipfile and Pipfile.lock. Is this intended?
> Right now running "pipenv install --dev" already installs collect_stata.

Yes, the `pipenv install -e .` could be removed with the README.md update.

**Comment by afuetterer** [comment]
I see.

**Comment by mpahl** [comment]
> I ran into this:
> https://github.com/ddionrails/ddi.py/tree/master/docs
> 
> Is this reusable in some way?

This is an old [Sphinx](http://www.sphinx-doc.org/en/master/) documentation. Should I revive it for collect_stata?

**Comment by hansendx** [comment]
No, we can create a new sphynx documentation with napoleon and the new docstrings.
