### ISSUE TITLE
Reduce number of blank lines

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/collect_stata#35]
See <https://www.python.org/dev/peps/pep-0008/#blank-lines> for reference.

There are a lot of blank lines in the code, that make the modules longer than necessary. For example these blank lines
https://github.com/ddionrails/collect_stata/blob/54f33d3d11e0b4e6ba1c4f989c56e293258c9b82/collect_stata/write_json.py#L181-L211
are not really needed to understand the function. It's an if statement.

**Comment by mpahl** [comment]
Done by @hansendx

**Comment by afuetterer** [comment]
This was only an example. There are still plenty of blank lines in the code base.

**Comment by afuetterer** [comment]
closing this.
