### ISSUE TITLE
German umlauts in labels are decoded incorrectly

### ISSUE THREAD

**Issue by hansendx** [ddionrails/collect_stata#48]
Maybe this is related: https://github.com/pandas-dev/pandas/issues/21244

**Comment by hansendx** [comment]
Example:

```python
{'kidgeb': {
      -6: '[
        -6
      ] Fragebogenversion mit geÃ¤nderter FilterfÃ¼hrung',
      -5: '[
        -5
      ] nicht im Fragebogen enthalten',
      -4: '[
        -4
      ] unzulÃ¤ssige Mehrfachantwort',
      -3: '[
        -3
      ] nicht valide',
      -2: '[
        -2
      ] trifft nicht zu',
      -1: '[
        -1
      ] keine Angabe'
    }
  }
```
Seems it was falsely decoded by pandas:
```python
"FilterfÃ¼hrung".encode("latin1").decode("utf8") == 'Filterführung'
```

**Comment by kwenzig** [comment]
Stata changed encoding to UTF-8 in their file format since Stata 14 (which ist dtaformat 118, c.f. https://www.stata.com/help.cgi?dtaversion and https://youtu.be/o68ZLxjw-1o). We are using the file format from Stata 12 (dta 115). One would have to check which versions can be imported by pandas.

**Comment by mpahl** [comment]
The error is in write_json.py.
If you add "ensure_ascii=False" in line 292 of write_json.py, the output should be correct.
```python
    with open(filename, "w") as json_file:
        json.dump(stat, json_file, indent=2, ensure_ascii=False)
```
